# Generated by Django 5.0.1 on 2024-02-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rango", "0002_auto_20240204_2355"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(default=""),
            preserve_default=False,
        ),
    ]
